export enum MessageActionTypes {
  ADD_MESSAGE = "ADD_MESSAGE",
  DELETE_MESSAGE = "ADD_MESSAGE",
  UPDATE_MESSAGE = "UPDATE_MESSAGE"
}

export enum UsersActionTypes {
  ADD_USER = "ADD_USER",
  DELETE_USER = "DELETE_USER",
  UPDATE_USER = "UPDATE_USER",
  SET_USERS_LIST = "SET_USERS_LIST",
  SET_USER_REF = "SET_USER_REF"
}

export enum AppActionsTypes {
  SET_APP_STATE = "SET_APP_STATE"
}
